export const VOLUMETRIC_PARAMS = [
  {
    paramName: 'chest',
    units: 'cm',
    name: 'Bust girth',
    paramGroup: 'volume_params',
    source: 'ISO 8559-1',
    equipment: 'Tape measure',
    definition: 'The measurement is taken around the fullest part of the bust point level',
    imageURI: '/volume/chest.jpg',
  },
  {
    paramName: 'under_bust_girth',
    units: 'cm',
    name: 'Under bust girth',
    paramGroup: 'volume_params',
    source: 'ISO 8559-1',
    equipment: 'Tape measure',
    definition: 'Horizontal girth of the body at the under bust level',
    imageURI: '/volume/under_bust_girth.jpg',
  },
  {
    paramName: 'upper_chest_girth',
    units: 'cm',
    name: 'Upper chest girth',
    paramGroup: 'volume_params',
    source: 'ISO 8559-1',
    equipment: 'Tape measure',
    definition: 'Chest measured from the bust level at center back, under the armpits and above the bust to the front.',
    imageURI: '/volume/upper_chest_girth.jpg',
  },
  {
    paramName: 'overarm_girth',
    units: 'cm',
    name: 'Overarm girth',
    paramGroup: 'volume_params',
    source: '3DLOOK',
    equipment: 'Tape measure',
    definition: 'Measure over the arm, across the bust level.',
    imageURI: '/volume/overarm_girth.png',
  },
  {
    paramName: 'waist',
    units: 'cm',
    name: 'Waist girth',
    paramGroup: 'volume_params',
    source: 'ISO 8559-1',
    equipment: 'Tape measure',
    definition: 'The measurement is taken around the waist level. Person stands upright with the abdomen relaxed.',
    imageURI: '/volume/waist.jpg',
  },
  {
    paramName: 'high_hips',
    units: 'cm',
    name: 'Upper hip girth',
    paramGroup: 'volume_params',
    source: 'ISO 8559-1',
    equipment: 'Tape measure',
    definition: 'The measurement is taken around the upper hip level',
    imageURI: '/volume/high_hips.jpg',
  },
  {
    paramName: 'low_hips',
    units: 'cm',
    name: 'Hip girth',
    paramGroup: 'volume_params',
    source: 'ISO 8559-1',
    equipment: 'Tape measure',
    definition: 'The measurement is taken around the fullest part of the hip',
    imageURI: '/volume/low_hips.jpg',
  },
  {
    paramName: 'bicep',
    units: 'cm',
    name: 'Upper-arm girth',
    paramGroup: 'volume_params',
    source: 'ISO 8559-1',
    equipment: 'Tape measure',
    definition: 'The measurement is taken around the fullest part of the bicep between the shoulder and elbow point',
    imageURI: '/volume/bicep.jpg',
  },
  {
    paramName: 'upper_bicep_girth',
    units: 'cm',
    name: 'Upper bicep girth',
    paramGroup: 'volume_params',
    source: '3DLOOK',
    equipment: 'Tape measure',
    definition: 'The maximum circumference of the bicep, taken 1" below the armhole bottom.',
    imageURI: '/volume/upper_bicep_girth.jpg',
  },
  {
    paramName: 'knee',
    units: 'cm',
    name: 'Knee girth',
    paramGroup: 'volume_params',
    source: 'ISO 8559-1',
    equipment: 'Tape measure',
    definition: 'The measurement is taken around the level of the centre point of kneecap. Person stands upright with legs shoulder width apart.',
    imageURI: '/volume/knee_girth.jpg',
  },
  {
    paramName: 'ankle',
    units: 'cm',
    name: 'Ankle girth',
    paramGroup: 'volume_params',
    source: 'ISO 8559-1',
    equipment: 'Tape measure',
    definition: 'The measurement is taken around the level of the outer ankle point. Person stands upright with legs shoulder width apart.',
    imageURI: '/volume/ankle.jpg',
  },
  {
    paramName: 'wrist',
    units: 'cm',
    name: 'Wrist girth',
    paramGroup: 'volume_params',
    source: 'ISO 8559-1',
    equipment: 'Tape measure',
    definition: 'The measurement is taken around the narrowest part at the level of wrist point.',
    imageURI: '/volume/wrist.jpg',
  },
  {
    paramName: 'calf',
    units: 'cm',
    name: 'Calf girth',
    paramGroup: 'volume_params',
    source: 'ISO 8559-1',
    equipment: 'Tape measure',
    definition: 'The measurement is taken around the fullest part of the calf. Person stands upright with legs shoulder width apart.',
    imageURI: '/volume/calf.jpg',
  },
  {
    paramName: 'thigh',
    units: 'cm',
    name: 'Thigh girth',
    paramGroup: 'volume_params',
    source: 'ISO 8559-1',
    equipment: 'Tape measure',
    definition: 'The measurement is taken around the fullest part of the thigh below the fold of the buttock. Person stands upright with legs shoulder width apart.',
    imageURI: '/volume/thigh.jpg',
  },
  {
    paramName: 'thigh_1_inch_below_crotch',
    units: 'cm',
    name: 'Thigh 1 inch below the crotch',
    paramGroup: 'volume_params',
    source: '3DLOOK',
    equipment: 'Tape measure',
    definition: 'The widest part of the thigh, 1” below the crotch, directly below the butt. Measure around the thigh at this point, keeping the measuring tape parallel to the floor.',
    imageURI: '/volume/thigh_1_inch_below_crotch.jpg',
  },
  {
    paramName: 'mid_thigh_girth',
    units: 'cm',
    name: 'Mid - thigh girth',
    paramGroup: 'volume_params',
    source: 'ISO 8559-1',
    equipment: 'Tape measure',
    definition: 'Horizontal girth of the thigh measured midway between the inside leg level and the centre point of knee cap.',
    imageURI: '/volume/mid_thigh_girth.jpg',
  },
  {
    paramName: 'neck',
    units: 'cm',
    name: 'Neck base girth',
    paramGroup: 'volume_params',
    source: 'ISO 8559-1',
    equipment: 'Tape measure',
    definition: 'The measurement is taken around neck base measured from the back neck point to the front neck point.',
    imageURI: '/volume/neck.jpg',
  },
  {
    paramName: 'abdomen',
    units: 'cm',
    name: 'Abdomen girth',
    paramGroup: 'volume_params',
    source: '3DLOOK',
    equipment: 'Tape measure',
    definition: 'The measurement is taken around the maximum anterior protrusion of the abdomen.',
    imageURI: '/volume/abdomen.jpg',
  },
  {
    paramName: 'armscye_girth',
    units: 'cm',
    name: 'Armscye girth',
    paramGroup: 'volume_params',
    source: 'ISO 8559-1',
    equipment: 'Tape measure',
    definition: 'Girth of the armscye measured from, and to, the shoulder point passing under the arm',
    imageURI: '/volume/armscye_girth.jpg',
  },
  {
    paramName: 'neck_girth',
    units: 'cm',
    name: 'Neck girth',
    paramGroup: 'volume_params',
    source: 'ISO 8559-1',
    equipment: 'Tape measure',
    definition: 'The measurement is taken around neck at the point just below the neck bulge (Adam’s apple) and measured perpendicular to the longitudinal axis of the neck.',
    imageURI: '/volume/neck_girth.jpg',
  },
  {
    paramName: 'neck_girth_relaxed',
    units: 'cm',
    name: 'Neck girth relaxed',
    paramGroup: 'volume_params',
    source: 'ISO 8559-1',
    equipment: 'Tape measure',
    definition: 'Girth of the neck at a point just below the bulge at the thyroid cartilage (Adam’s apple) and measured perpendicular to the longitudinal axis of the neck adding a half inch to the measurement to ensure comfort.',
    imageURI: '/volume/neck_girth.jpg',
  },
  {
    paramName: 'forearm',
    units: 'cm',
    name: 'Forearm girth flexed',
    paramGroup: 'volume_params',
    source: 'ISO 7250-1',
    equipment: 'Tape measure',
    definition: 'The measurement is taken around the fullest part of the forearm, one-third of the distance from olecranon to wrist.',
    imageURI: '/volume/forearm.jpg',
  },
  {
    paramName: 'elbow_girth',
    units: 'cm',
    name: 'Elbow girth',
    paramGroup: 'volume_params',
    source: 'ISO 8559-1',
    equipment: 'Tape measure',
    definition: 'Girth of the arm at the elbow point',
    imageURI: '/volume/elbow_girth.jpg',
  },
];

export const LINEAR_PARAMS = [
  // all front
  {
    paramName: 'body_height',
    units: 'cm',
    name: 'Neck to upper hip length',
    paramGroup: 'front_params',
    source: '3DLOOK',
    equipment: 'Tape measure',
    definition: 'Vertical distance from the neck point to the upper hip level.',
    imageURI: '/linear/body_height.jpg',
  },
  {
    paramName: 'outseam',
    units: 'cm',
    name: 'Outside leg length',
    paramGroup: 'front_params',
    source: 'ISO 8559-1',
    equipment: 'Tape measure',
    definition: 'Distance down the side of the body from the waist level following the contour to the hip level, then vertically to the ground.',
    imageURI: '/linear/outseam.jpg',
  },
  {
    paramName: 'outseam_from_upper_hip_level',
    units: 'cm',
    name: 'Outside leg length from upper hip level',
    paramGroup: 'front_params',
    source: '3DLOOK',
    equipment: 'Tape measure',
    definition: 'Distance down the side of the body from the highest point of the hip bone (Upper hip girth) following the contour to the hip level (Hip girth), then vertically to just where shoe heel meets sole (1 inch below the ankles).',
    imageURI: '/linear/outseam_from_upper_hip_level.jpg',
  },
  {
    paramName: 'inseam',
    units: 'cm',
    name: 'Inside leg length',
    paramGroup: 'front_params',
    source: 'ISO 8559-1',
    equipment: 'Tape measure',
    definition: 'Vertical distance between the inside leg level and outer ankle point',
    imageURI: '/linear/inseam.jpg',
  },
  {
    paramName: 'inside_leg_length_to_the_1_inch_above_the_floor',
    units: 'cm',
    name: 'Inside leg length to the 1 inch above the floor',
    paramGroup: 'front_params',
    source: '3DLOOK',
    equipment: 'Tape measure',
    definition: 'Vertical distance from the inside leg level to the 1 inch above the floor.',
    imageURI: '/linear/inseam.jpg',
  },
  {
    paramName: 'inside_crotch_length_to_mid_thigh',
    units: 'cm',
    name: 'Inside crotch length to mid-thigh',
    paramGroup: 'front_params',
    source: '3DLOOK',
    equipment: 'Tape measure',
    definition: 'Distance from the inside leg level to the mid-thigh level following the contour of the body.',
    imageURI: '/linear/inside_crotch_length_to_mid_thigh.jpg',
  },
  {
    paramName: 'inside_crotch_length_to_knee',
    units: 'cm',
    name: 'Inside crotch length to knee',
    paramGroup: 'front_params',
    source: '3DLOOK',
    equipment: 'Tape measure',
    definition: 'Distance from the inside leg level to the knee level following the contour of the body.',
    imageURI: '/linear/inside_crotch_length_to_knee.jpg',
  },
  {
    paramName: 'inside_crotch_length_to_calf',
    units: 'cm',
    name: 'Inside crotch length to calf',
    paramGroup: 'front_params',
    source: '3DLOOK',
    equipment: 'Tape measure',
    definition: 'Distance from the inside leg level to the calf level following the contour of the body.',
    imageURI: '/linear/inside_crotch_length_to_knee.jpg',
  },
  {
    paramName: 'crotch_length',
    units: 'cm',
    name: 'Straight body rise',
    paramGroup: 'front_params',
    source: 'ISO 8559-1',
    equipment: 'Sliding calliper',
    definition: 'Vertical distance between the waist and inside leg levels.',
    imageURI: '/linear/crotch_length.jpg',
  },
  {
    paramName: 'sleeve_length',
    units: 'cm',
    name: 'Outer arm length',
    paramGroup: 'front_params',
    source: 'ISO 8559-1',
    equipment: 'Tape measure',
    definition: 'Distance from shoulder point to wrist point.',
    imageURI: '/linear/sleeve_length.jpg',
  },
  {
    paramName: 'underarm_length',
    units: 'cm',
    name: 'Underarm length',
    paramGroup: 'front_params',
    source: 'ISO 8559-1',
    equipment: 'Tape measure',
    definition: 'Distance between the armpit front fold point and palm side of the wrist at a level of the wrist point.',
    imageURI: '/linear/underarm_length.jpg',
  },
  {
    paramName: 'back_neck_point_to_wrist_length',
    units: 'cm',
    name: 'Back neck point to wrist length',
    paramGroup: 'front_params',
    source: 'ISO 8559-1',
    equipment: 'Tape measure',
    definition: 'Distance across the shoulder and down the arm from the back neck point over the shoulder point and the elbow point to the wrist point',
    imageURI: '/linear/back_neck_point_to_wrist_length.jpg',
  },
  {
    paramName: 'back_neck_point_to_wrist_length_1_5_inch',
    units: 'cm',
    name: 'Back neck point to 1.5" past the wrist point',
    paramGroup: 'front_params',
    source: '3DLOOK',
    equipment: 'Tape measure',
    definition: 'The distance across the shoulder and down the arm from the back neck point over the shoulder point and the elbow point to 1.5" past the wrist point or wrist bend.',
    imageURI: '/linear/back_neck_point_to_wrist_length_1_5_inch.jpg',
  },
  {
    paramName: 'high_hips',
    units: 'cm',
    name: 'Upper hip breadth',
    paramGroup: 'front_params',
    source: '3DLOOK',
    equipment: 'Sliding calliper',
    definition: 'Horizontal distance across the upper hips.',
    imageURI: '/linear/high_hips.jpg',
  },
  {
    paramName: 'shoulders',
    units: 'cm',
    name: 'Front shoulder width',
    paramGroup: 'front_params',
    source: '3DLOOK',
    equipment: 'Tape measure',
    definition: 'Distance across the front between the left and right shoulder points.',
    imageURI: '/linear/shoulders.jpg',
  },
  {
    paramName: 'chest_top',
    units: 'cm',
    name: 'Chest width',
    paramGroup: 'front_params',
    source: '3DLOOK',
    equipment: 'Sliding calliper',
    definition: 'Horizontal distance of the torso between the right and left axilla.',
    imageURI: '/linear/chest_top.jpg',
  },
  {
    paramName: 'jacket_length',
    units: 'cm',
    name: 'Jacket length',
    paramGroup: 'front_params',
    source: '3DLOOK',
    equipment: 'Tape measure',
    definition: 'Vertical distance from the side neck point to the middle of thumb.',
    imageURI: '/linear/jacket_length.jpg',
  },
  {
    paramName: 'shoulder_length',
    units: 'cm',
    name: 'Shoulder length',
    paramGroup: 'front_params',
    source: 'ISO 8559-1',
    equipment: 'Tape measure',
    definition: 'Distance from the side neck point to the shoulder point.',
    imageURI: '/linear/shoulder_length.jpg',
  },
  {
    paramName: 'shoulder_slope',
    units: 'deg',
    name: 'Shoulder slope',
    paramGroup: 'front_params',
    source: 'ISO 8559-1',
    equipment: 'Inclinometer',
    definition: 'The value (in degrees) of the angle of inclination with the inclinometer placed on the shoulder following a line joining the shoulder and side neck points.',
    imageURI: '/linear/shoulder_slope.jpg',
  },
  {
    paramName: 'neck',
    units: 'cm',
    name: 'Neck base width',
    paramGroup: 'front_params',
    source: 'ISO 8559-1',
    equipment: 'Sliding calliper',
    definition: 'Horizontal distance between the side neck points.',
    imageURI: '/linear/neck.jpg',
  },
  {
    paramName: 'waist_to_low_hips',
    units: 'cm',
    name: 'Waist to hip length',
    paramGroup: 'front_params',
    source: '3DLOOK',
    equipment: 'Sliding calliper',
    definition: 'Vertical distance from the waist level to the hip level.',
    imageURI: '/linear/waist_to_low_hips.jpg',
  },
  {
    paramName: 'waist_to_knees',
    units: 'cm',
    name: 'Waist to knee length',
    paramGroup: 'front_params',
    source: '3DLOOK',
    equipment: 'Sliding calliper',
    definition: 'Vertical distance from the waist level to the knee level.',
    imageURI: '/linear/waist_to_knees.jpg',
  },
  {
    paramName: 'abdomen_to_upper_knee_length',
    units: 'cm',
    name: 'Abdomen to upper knee length',
    paramGroup: 'front_params',
    source: '3DLOOK',
    equipment: 'Sliding calliper',
    definition: 'Vertical distance from the abdomen level to the upper knee level.',
    imageURI: '/linear/abdomen_to_upper_knee_length.jpg',
  },
  {
    paramName: 'upper_knee_to_ankle',
    units: 'cm',
    name: 'Upper knee girth to ankle girth',
    paramGroup: 'front_params',
    source: '3DLOOK',
    equipment: 'Sliding calliper',
    definition: 'The measurement is taken starting from 3" above the knee central point to the leg\'s ankle bone.',
    imageURI: '/linear/upper_knee_to_ankle.jpg',
  },
  {
    paramName: 'nape_to_waist_centre_back',
    units: 'cm',
    name: 'Back neck point to waist',
    paramGroup: 'front_params',
    source: 'ISO 8559-1',
    equipment: 'Tape measure',
    definition: 'Distance from the back neck point to waist level following the contour of the body.',
    imageURI: '/linear/nape_to_waist_centre_back.jpg',
  },
  {
    paramName: 'shoulder_to_waist',
    units: 'cm',
    name: 'Side neck point to waist level',
    paramGroup: 'front_params',
    source: 'ISO 8559-1',
    equipment: 'Tape measure',
    definition: 'Distance from the side neck point to the waist level following the contour of the body',
    imageURI: '/linear/shoulder_to_waist.jpg',
  },
  {
    paramName: 'side_neck_point_to_armpit',
    units: 'cm',
    name: 'Side neck point to armpit front fold point',
    paramGroup: 'front_params',
    source: '3DLOOK',
    equipment: 'Tape measure',
    definition: 'Distance from the side neck point to the armpit front fold point following the contour of the body.',
    imageURI: '/linear/side_neck_point_to_armpit.jpg',
  },
  {
    paramName: 'back_neck_height',
    units: 'cm',
    name: 'Back neck height',
    paramGroup: 'front_params',
    source: 'ISO 8559-1',
    equipment: 'Anthropometer',
    definition: 'Vertical distance from back neck point to the ground.',
    imageURI: '/linear/back_neck_height.jpg',
  },
  {
    paramName: 'bust_height',
    units: 'cm',
    name: 'Bust height',
    paramGroup: 'front_params',
    source: 'ISO 8559-1',
    equipment: 'Anthropometer',
    definition: 'Vertical distance from the bust point to the ground.',
    imageURI: '/linear/bust_height.jpg',
  },
  {
    paramName: 'hip_height',
    units: 'cm',
    name: 'Hip height',
    paramGroup: 'front_params',
    source: 'ISO 8559-1',
    equipment: 'Anthropometer',
    definition: 'Vertical distance from the hip level to the ground.',
    imageURI: '/linear/hip_height.jpg',
  },
  {
    paramName: 'upper_hip_height',
    units: 'cm',
    name: 'Upper hip height',
    paramGroup: 'front_params',
    source: 'ISO 8559-1',
    equipment: 'Anthropometer',
    definition: 'Vertical distance from the upper hip level to the ground.',
    imageURI: '/linear/upper_hip_height.jpg',
  },
  {
    paramName: 'knee_height',
    units: 'cm',
    name: 'Knee height',
    paramGroup: 'front_params',
    source: 'ISO 8559-1',
    equipment: 'Anthropometer',
    definition: 'Vertical distance from the centre point of kneecap to the ground.',
    imageURI: '/linear/knee_height.jpg',
  },
  {
    paramName: 'outer_ankle_height',
    units: 'cm',
    name: 'Outer ankle height',
    paramGroup: 'front_params',
    source: 'ISO 8559-1',
    equipment: 'Anthropometer',
    definition: 'Vertical distance from the outer ankle point to the ground.',
    imageURI: '/linear/outer_ankle_height.jpg',
  },
  {
    paramName: 'waist_height',
    units: 'cm',
    name: 'Waist Height',
    paramGroup: 'front_params',
    source: 'ISO 8559-1',
    equipment: 'Anthropometer',
    definition: 'Vertical distance from the waist level to the ground.',
    imageURI: '/linear/waist_height.jpg',
  },
  {
    paramName: 'inside_leg_height',
    units: 'cm',
    name: 'Inside leg height',
    paramGroup: 'front_params',
    source: 'ISO 8559-1',
    equipment: 'Anthropometer',
    definition: 'Vertical distance from the inside leg level to the ground.',
    imageURI: '/linear/inside_leg_height.jpg',
  },
  {
    paramName: 'across_back_shoulder_width',
    units: 'cm',
    name: 'Across back shoulder width',
    paramGroup: 'front_params',
    source: 'ISO 8559-1',
    equipment: 'Tape measure',
    definition: 'Distance from the left shoulder point, through the back neck to the right shoulder points',
    imageURI: '/linear/across_back_shoulder_width.jpg',
  },
  {
    paramName: 'across_back_width',
    units: 'cm',
    name: 'Across back width',
    paramGroup: 'front_params',
    source: 'ISO 8559-1',
    equipment: 'Tape measure',
    definition: 'Distance across the back between the left and right arm scye lines. The level of measurement is midway between the shoulder point and the armpit back fold point.',
    imageURI: '/linear/across_back_width.jpg',
  },
  {
    paramName: 'total_crotch_length',
    units: 'cm',
    name: 'Total crotch Length',
    paramGroup: 'front_params',
    source: 'ISO 8559-1',
    equipment: 'Tape measure',
    definition: 'Distance from the centre of the waist level at the front of the body, through the crotch (inside leg level), to the centre of the back waist level. Avoid any constriction at the crotch.',
    imageURI: '/linear/total_crotch_length.jpg',
  },
  {
    paramName: 'waist',
    units: 'cm',
    name: 'Waist breadth',
    paramGroup: 'front_params',
    source: '3DLOOK',
    equipment: 'Sliding calliper',
    definition: 'Horizontal distance across the waist. ',
    imageURI: '/linear/waist.jpg',
  },
  {
    paramName: 'neck_length',
    units: 'cm',
    name: 'Neck length',
    paramGroup: 'front_params',
    source: '3DLOOK',
    equipment: 'Tape measure',
    definition: 'Distance from the mandibular angle to the side neck point',
    imageURI: '/linear/neck_length.jpg',
  },
  {
    paramName: 'upper_arm_length',
    units: 'cm',
    name: 'Upper arm length',
    paramGroup: 'front_params',
    source: 'ISO 8559-1',
    equipment: 'Tape measure',
    definition: 'Distance from the shoulder to the elbow points',
    imageURI: '/linear/upper_arm_length.jpg',
  },
  {
    paramName: 'lower_arm_length',
    units: 'cm',
    name: 'Lower arm length',
    paramGroup: 'front_params',
    source: 'ISO 8559-1',
    equipment: 'Tape measure',
    definition: 'Distance from the elbow to the wrist points',
    imageURI: '/linear/lower_arm_length.jpg',
  },
  {
    paramName: 'upper_hip_to_hip_length',
    units: 'cm',
    name: 'Upper hip to hip length',
    paramGroup: 'front_params',
    source: '3DLOOK',
    equipment: 'Sliding calliper',
    definition: 'Vertical distance from the upper hip to hip level.',
    imageURI: '/linear/upper_hip_to_hip_length.jpg',
  },
  {
    paramName: 'back_shoulder_width',
    units: 'cm',
    name: 'Back shoulder width',
    paramGroup: 'front_params',
    source: 'ISO 8559-1',
    equipment: 'Tape measure',
    definition: 'Distance across the back between the left and right shoulder points. ',
    imageURI: '/linear/back_shoulder_width.jpg',
  },
  {
    paramName: 'rise',
    units: 'cm',
    name: 'Rise',
    paramGroup: 'front_params',
    source: '3DLOOK',
    equipment: 'Sliding calliper',
    definition: 'Vertical distance between the upper hip and inside leg levels.',
    imageURI: '/linear/rise.jpg',
  },
  {
    paramName: 'back_neck_to_hip_length',
    units: 'cm',
    name: 'Back neck to hip length',
    paramGroup: 'front_params',
    source: '3DLOOK',
    equipment: 'Sliding calliper',
    definition: 'Vertical distance from back neck point to the hip level.',
    imageURI: '/linear/back_neck_to_hip_length.jpg',
  },
  {
    paramName: 'torso_height',
    units: 'cm',
    name: 'Torso height',
    paramGroup: 'front_params',
    source: 'ISO 8559-1',
    equipment: 'Sliding calliper',
    definition: ' Vertical distance from back neck point to the inside leg level.',
    imageURI: '/linear/torso_height.jpg',
  },
  {
    paramName: 'front_crotch_length',
    units: 'cm',
    name: 'Front crotch length',
    paramGroup: 'front_params',
    source: '3DLOOK',
    equipment: 'Tape measure',
    definition: 'Distance from the belly button, to the centre of the inside of the thigh at the height of the inside leg level.',
    imageURI: '/linear/front_crotch_length.jpg',
  },
  {
    paramName: 'back_crotch_length',
    units: 'cm',
    name: 'Back crotch length',
    paramGroup: 'front_params',
    source: '3DLOOK',
    equipment: 'Tape measure',
    definition: 'Distance from the centre of the back in parallel with the belly button level, to the centre of the inside of the thigh at the height of the inside leg level.',
    imageURI: '/linear/back_crotch_length.jpg',
  },

  // all side
  {
    paramName: 'side_upper_hip_level_to_knee',
    units: 'cm',
    name: 'Side upper hip level to knee',
    paramGroup: 'side_params',
    source: '3DLOOK',
    equipment: 'Tape measure',
    definition: 'Distance from the upper hip level to the knee level following the contour of the body.',
    imageURI: '/linear/side_upper_hip_level_to_knee.jpg',
  },
  {
    paramName: 'side_neck_point_to_upper_hip',
    units: 'cm',
    name: 'Side neck point to upper hip',
    paramGroup: 'side_params',
    source: '3DLOOK',
    equipment: 'Tape measure',
    definition: 'Distance from the side neck point to the upper hip level following the contour of the body',
    imageURI: '/linear/side_neck_point_to_upper_hip.jpg',
  },
  {
    paramName: 'neck_to_chest',
    units: 'cm',
    name: 'Side neck to bust point',
    paramGroup: 'side_params',
    source: 'ISO 8559-1',
    equipment: 'Tape measure',
    definition: 'Distance from the side neck point to the bust point following the contour of the body.',
    imageURI: '/linear/neck_to_chest.jpg',
  },
  {
    paramName: 'chest_to_waist',
    units: 'cm',
    name: 'Side bust point to waist level',
    paramGroup: 'side_params',
    source: '3DLOOK',
    equipment: 'Tape measure',
    definition: 'Distance from side bust point vertically straight to the waist level',
    imageURI: '/linear/chest_to_waist.jpg',
  },
  {
    paramName: 'waist_to_ankle',
    units: 'cm',
    name: 'Side waist level to ankles',
    paramGroup: 'side_params',
    source: '3DLOOK',
    equipment: 'Tape measure',
    definition: 'Distance from side waist level to the ankle level following the contour of the body.',
    imageURI: '/linear/waist_to_ankle.jpg',
  },
  {
    paramName: 'shoulders_to_knees',
    units: 'cm',
    name: 'Side neck point to knee',
    paramGroup: 'side_params',
    source: '3DLOOK',
    equipment: 'Tape measure',
    definition: 'Distance from front the side neck point following the contour of the body to the knee level.',
    imageURI: '/linear/shoulders_to_knees.jpg',
  },
];
